### ISSUE TITLE
iterator points to an invalid object when copying a vector into an array of vectors

### ISSUE THREAD

**Issue by misael-diaz** [misael-diaz/OpenBDS#62]
the following code snippet shows what needs to be avoided:
```
vectors = f()
```
where `f()` is a function that returns a vector and `vectors` is an array of vectors

As a result the iterators point to the same memory address unless the iterator of vector is `NULL`.

workaround until the bug is fixed is the following:
```
do i = first:last
    vectors(i) = f()
end do
```

**TODO**

- [x] Try defining what it means to copy a vector into an array of vectors and overload the type-bound assign operator with the method. (Did not work see [comment](https://github.com/misael-diaz/OpenBDS/issues/62#issuecomment-873590162) below.)
- [x] Try doing the pointer association after the `vector_vector_t_copy` subroutine returns. And do it in a subroutine where only the vector itself is passed as an argument.
- [x] implement validate method to validate the iterators whenever needed #103
- [x] check if this is a bug of the compiler and report it if it has not been reported already

**Comment by misael-diaz** [comment]
A more thorough inspection of the problem has shown that the iterators have `outlived' their targets. The address the iterators point to is the same and does not belong to any of the internal arrays of the array of vectors.

**Comment by misael-diaz** [comment]
**wontfix**
The problem cannot be easily resolved since the compiler synthesizes the ``assignment'' of a vector to an array of vectors instead of using the implemented method. If the assignment is carried out elementwise, the implemented ``assignment'' method is invoked and the iterators point to internal array as they should.

For the time being the only way to create an array of vectors from a vector is to do so in an element-by-element fashion.

I did not actually try the second item in the checklist but I know that validating the iterators after the synthesized assignment takes place will fix the problem. However, I do not believe it's a practical solution because it forces the user to do an additional step which should be handled otherwise (under covers).
