### ISSUE TITLE
push array into vector

### ISSUE THREAD

**Issue by misael-diaz** [misael-diaz/OpenBDS#63]
Consider adding support for pushing an array into vectors

**Comments**
The size of the vector follows the sequence: 8, 16, 32, 64, ..., 2 ^ (n - 1), 2 ^ n

Make it so that pushing an array to leads to a vector having a size that can be represented by two to the nth power (integer). The proposed approach is to use bitwise operations and intrinsics when the array size is greater than the current vector size:

- find the number of elements in the array by the `size` intrinsic
- obtain the MSB and left-shift to create a mask
- Bitwise AND the array-size with itself (all 64-bits will be set LOW) or assign a value of zero
- Bitwise OR with the mask to set left-shifted bit HIGH so that the new vector size is two to the power of some power n, 2^n

Note that we always ask for twice the array-size by left-shifting the MSB so that another array of the same size can be pushed to the vector without having to reallocate it.

If the array can be pushed without resizing the vector, then no memory reallocation will take place.
 

**TODO**
- [x] complete task #68
- [x] partition by methods (examples:  `push_back`, `erase`, etc. methods in their own submodule) so that you can omit committing anything related to the experimental `erase` methods when you push to the main branch. This has been assigned in task #70
- [x] partition grow method  #72 
- [x] refactor writing data into vector #73
- [x] refactor string allocations #76
- [x] use bit operations to double the size of the vector
- [x] implement the `fill` constructor #88
- [x] int32 types
- [x] int64 types
- [x] real64 types
- [x] vector type (push array of vectors)
