### ISSUE TITLE
implement the fill constructor [vector]

### ISSUE THREAD

**Issue by misael-diaz** [misael-diaz/OpenBDS#88]
implement a `fill` constructor based on the c++ fill [constructor](https://www.cplusplus.com/reference/vector/vector/vector/) which takes as argument the number of copies and a value.

Note that some work has been done before creating the issue. What's pending is setting the internal error message which is displayed to user when trying to push mixed types to a vector of built-in type.

**TODO**
- [x] set the internal error message #87 
- [x] partition the code further #89
- [x] test for aliasing #91
- [x] handle filling the vector with `empty` vectors #90
